# GitHub Enterprise Documentation:
# - https://github.com/andyfeller/issueops-createrepo
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
#
name: Create Repository
description: Request creation of GitHub Repository
labels:
  - create-repo
body:
  - type: markdown
    attributes:
      value: |
        Need a new repository?

        Fill out this form to get it started.
        More info about the repository product, please check [GitHub Repository]().
  - type: dropdown
    id: organization
    attributes:
      label: Organization
      description: Select an organization to create the repo.
      options:
        - dnb-acme
        - dnb-tooling
      default: 0
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: Great repository names are short and memorable.
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
  - type: dropdown
    id: visibility
    attributes:
      label: Visibility
      description: |
        - **Internal**: Enterprise members can see this repository. You choose who can commit.
        - **Private**: You choose who can see and commit to this repository.
      options:
        - Internal
        - Private
      default: 0
    validations:
      required: true
  - type: textarea
    id: private-visibility-justification
    attributes:
      label: Private visibility justification
      description: |
        Understanding the business case for `Private` visibility instead of `Internal`.
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select a type. For more info about the repo types, please check [Repository Archetypes]().
      options:
        - Action
        - FunctionApp
        - PSModule
        - Workflow
        - '-----------'
        - Bare
        - Template
      default: 0
    validations:
      required: true
  - type: input
    id: business-application-id
    attributes:
      label: Business Application ID
      description: The id used to link the business application to a CI in the CMBD. Must start with 'BS' or 'BSN'.
    validations:
      required: true
